inv = {'nodes':(0,'undt'), 
       'edges':(0,'undt'), 
       'maxdeg':(0,'undt'), 
       'mindeg':(0,'undt'),
       'chr':(0,'undt'),
       'omega':(0,'undt'),
       'alpha0':(0,'undt'),
       'alpha1':(0,'undt'),
       'beta0':(0,'undt'),
       'beta1':(0,'undt'),
       'theta0':(0,'undt'),
       'theta1':(0,'undt'),
       'radius':(0,'undt'),
       'diam':(0,'undt'),
       'genus':(0,'undt'),
       'nconn':(0,'undt'),
       'econn':(0,'undt'),
       'chil':(0,'undt'),
       'girth':(0,'undt'),
       'circ':(0,'undt'),
       'ncomp':(0,'undt'),
       'xnum':(0,'undt'),
       'arbor':(0,'undt'),
       'dom':(0,'undt'),
       'bwidth':(0,'undt'),
       'thick':(0,'undt'),
       'lambda':(0,'undt'),
       'compl':'undt',
       'bipart':'undt',
       'connct':'undt',
       'forest':'undt',
       'tree':'undt',
       'cycle':'undt',
       'reg':'undt',
       'hamil':'undt',
       'planar':'undt'}
       
       